### ISSUE TITLE
setup.py should not live in the root

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-contribs#1]
There should be the possibility to install just single or a portion of all contrib apps so basically each app should have its own `setup.py`

**Comment by ricardogsilva** [comment]
In addition to setup.py, the whole repo structure should be organized differently.

If each contrib module is to be installed separately, then the is no need for a dir structure like

`geonode-contribs/geonode_contribs/<contrib-package>`

we can stick with

`geonode-contribs/<contrib-package>`

**Comment by capooti** [comment]
My idea was that there is just one library with all of the contrib modules. We can then change if there will be ore modules, now there are just a couple of ones.

**Comment by capooti** [comment]
I am totally open anyway with your idea, so if you merge the PR I will adapt the other apps to the same structure.
One thing to keep in mind is that we will need to upload each distinct package to pypi, so more administrative work to keep in consideration

**Comment by francbartoli** [comment]
it's true @capooti but definitively more cleaned and manageable installation

**Comment by capooti** [comment]
Great, as soon as you change the structure I will update my setup accordingly. Just drop a message here when done.

**Comment by afabiani** [comment]
I agree, the additional "geonode_contribs" is redoundant. Please proceed with the change of the structure.
