### ISSUE TITLE
The app label 'keycloak-role' is not a valid Python identifier

### ISSUE THREAD

**Issue by WernerRaath** [GeoNode/geonode-contribs#138]
When I use this with a fresh installed [GeoNode Project](https://github.com/GeoNode/geonode-project) and follow [your README](https://github.com/GeoNode/geonode-contribs/blob/master/django-geonode-keycloak/README.md), I get the following error on container startup:
```
django.core.exceptions.ImproperlyConfigured: The app label 'keycloak-role' is not a valid Python identifier.
```
I am guessing that the file in question would be [django-geonode-keycloak/keycloakrole/apps.py](https://github.com/GeoNode/geonode-contribs/blob/master/django-geonode-keycloak/keycloakrole/apps.py)

**Comment by WernerRaath** [comment]
I got it to work after downloading the repo and replacing `label = 'keycloak-role'` with `label = 'keycloakrole'`

**Comment by afabiani** [comment]
Can you send a PR maybe?

**Comment by Zetten** [comment]
Following this change there's an error thrown when redirecting after hitting 'Sync Roles' (although it seems to still do the job just fine). I think the label needs to be updated here as well:

https://github.com/GeoNode/geonode-contribs/blob/master/django-geonode-keycloak/keycloakrole/views.py#L33

I'm not sure if there are other things that should perhaps be changed for consistency as well, like the package under `templates`.

**Comment by WernerRaath** [comment]
You think we can close this one?

**Comment by AlexGacon** [comment]
Apparently the fix is not enough : the templates folder still has a reference on keycloak-role

**Comment by WernerRaath** [comment]
This is the only template where `keycloak-role` was referenced which is now `keycloakrole`: https://github.com/GeoNode/geonode-contribs/blob/master/django-geonode-keycloak/keycloakrole/templates/admin/keycloakrole/keycloakrole/change_list.html
